#!/usr/bin/env python3
"""
Generates the layered summit illustration used by the animated homepage hero.
Layers: land (ranges + mountain + trail), front (mist + forest). Sky, sun, the
orange track and the athlete are drawn and animated in SummitHero.tsx.

    python3 scripts/generate-summit.py
"""
import math, random, re
W,H=1600,1000
DX,DY=150,24
def ridge(base, amp, seed, peaks, step=20):
    pts=[]
    for x in range(0,W+step,step):
        n=(math.sin(x*0.007+seed)*0.5+math.sin(x*0.019+seed*2.3)*0.3+math.sin(x*0.043+seed*3.1)*0.2)
        y=base-amp*n
        for px,ph,pw in peaks:
            y-=ph*max(0,1-abs(x-px)/pw)**1.35
        pts.append(f"{x},{y:.1f}")
    return "M0,%d L%s L%d,%d Z"%(H," L".join(pts),W,H)
def sh(path):
    return re.sub(r'(-?\d+\.?\d*),(-?\d+\.?\d*)', lambda m: f"{float(m.group(1))+DX:g},{float(m.group(2))+DY:g}", path)
apex=(1000+DX,300+DY)
main_lit=sh("M-150,800 L0,795 L180,760 L300,700 L430,640 L520,560 L585,590 L700,470 L770,430 L815,455 L905,370 L1000,300 L1040,470 L990,640 L960,800 L940,1000 L-150,1000 Z")
main_shadow=sh("M1000,300 L1062,352 L1100,346 L1180,420 L1215,408 L1330,520 L1440,575 L1600,640 L1700,680 L1700,1000 L940,1000 L960,800 L990,640 L1040,470 Z")
rim=sh("M430,640 L520,560 L585,590 L700,470 L770,430 L815,455 L905,370 L1000,300")
rocks=[sh(p) for p in ["M905,370 L880,440 L895,500","M770,430 L760,500","M1000,300 L975,380","M1062,352 L1050,420","M1180,420 L1160,480"]]
trail=sh("M640,860 L760,800 L700,760 L830,700 L790,660 L900,600 L870,560 L950,470 L930,430 L985,340")
random.seed(7)
fg_base=900
trees=[]; x=10
while x<W:
    h=random.randint(38,82); w=h*0.42
    y=fg_base-18*math.sin(x*0.004+1.2)-10*math.sin(x*0.013)+6
    trees.append(f'<path d="M{x:.0f},{y-h:.0f} L{x+w/2:.0f},{y:.0f} L{x-w/2:.0f},{y:.0f} Z"/>')
    x+=random.randint(18,46)
fg="M0,1000 L"+" L".join(f"{x},{fg_base-18*math.sin(x*0.004+1.2)-10*math.sin(x*0.013):.1f}" for x in range(0,W+20,20))+f" L{W},1000 Z"
c="#232C26"
_unused=f'''<g transform="translate({apex[0]} {apex[1]+1}) scale(1.25)" fill="{c}" stroke="{c}" stroke-linecap="round" stroke-linejoin="round">
  <path d="M-3.2 -22 L-7.5 -0.5 M3.2 -22 L7 -0.5" stroke-width="4.6" fill="none"/>
  <path d="M5 -39.5 C9.5 -39 10 -35 9.6 -30 C9.3 -26.5 7.5 -25 5.2 -25.5 Z" stroke="none" fill="#3B4A3F"/>
  <path d="M-6 -41 C-7 -35 -6.2 -28 -5 -21 L5 -21 C6.2 -28 7 -35 6 -41 C3 -42.4 -3 -42.4 -6 -41 Z" stroke="none"/>
  <path d="M-5 -40 L-9.5 -52 L-11.5 -63.5 M5 -40 L9.5 -52 L11.5 -63.5" stroke-width="3.4" fill="none"/>
  <circle cx="0" cy="-48" r="4.9" stroke="none"/>
</g>'''

trail_full = trail + f" L{apex[0]},{apex[1]}"
defs = f"""<linearGradient id="pf-lit" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#9DA77A"/><stop offset="0.5" stop-color="#7F8E66"/><stop offset="1" stop-color="#5F7052"/></linearGradient>
<linearGradient id="pf-shade" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#5E6C52"/><stop offset="1" stop-color="#46553F"/></linearGradient>
<linearGradient id="pf-rim" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#E7B07A" stop-opacity="0"/><stop offset="1" stop-color="#E7A46A" stop-opacity="0.85"/></linearGradient>
<filter id="pf-soft" x="-20%" y="-200%" width="140%" height="500%"><feGaussianBlur stdDeviation="18"/></filter>"""
land = f"""<path d="{ridge(660,18,0.4,[(420,55,320),(1480,130,260)])}" fill="#C9D1C3"/>
<path d="{ridge(705,16,2.1,[(160,40,260),(640,55,300),(1450,140,300)])}" fill="#B2BDAA"/>
<path d="{main_lit}" fill="url(#pf-lit)"/>
<path d="{main_shadow}" fill="url(#pf-shade)"/>
<path d="{rim}" fill="none" stroke="url(#pf-rim)" stroke-width="5" stroke-linejoin="round" opacity="0.9"/>
<g fill="none" stroke="#EAD9B8" stroke-opacity="0.35" stroke-width="2">{"".join(f'<path d="{r}"/>' for r in rocks)}</g>
<path d="{trail_full}" fill="none" stroke="#F1E3C6" stroke-opacity="0.6" stroke-width="2.4" stroke-dasharray="7 9" stroke-linecap="round"/>"""
front = f"""<g filter="url(#pf-soft)" fill="#F7EFE2"><ellipse cx="260" cy="760" rx="420" ry="34" opacity="0.5"/><ellipse cx="900" cy="790" rx="520" ry="30" opacity="0.4"/><ellipse cx="1460" cy="740" rx="380" ry="26" opacity="0.45"/></g>
<path d="{ridge(850,18,5.3,[(260,30,300),(1300,60,340)])}" fill="#56684F"/>
<g fill="#2E3B31">{"".join(trees)}</g>
<path d="{fg}" fill="#2E3B31"/>"""
import json, sys
def one(s): return " ".join(s.split())
out = f"""/* Generated by scripts/generate-summit.py. Do not edit by hand. */
export const SUMMIT_W = {W};
export const SUMMIT_H = {H};
export const SUMMIT_APEX = {{ x: {apex[0]}, y: {apex[1]} }} as const;
export const SUMMIT_TRAIL = {json.dumps(trail_full)};
export const SUMMIT_DEFS = {json.dumps(one(defs))};
export const SUMMIT_LAND = {json.dumps(one(land))};
export const SUMMIT_FRONT = {json.dumps(one(front))};
"""
path = sys.argv[1] if len(sys.argv) > 1 else "src/components/summit-scene.ts"
open(path, "w").write(out)
print("wrote", path, len(out))
